# This docker-compose.yml file is used for the tests.
# It deploys an empty mongodb and a redis.

version: '3'
services:
  backend:
    image: mongo:latest
    container_name: cmdproxy-backend
    networks:
      - overlay
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=cmdproxy-testdb

  broker:
    image: redis:latest
    container_name: cmdproxy-broker
    networks:
      - overlay
    ports:
      - "6379:6379"
    
  cmdproxy:
    build: .
    image: cmdproxy.rs:volatile
    container_name: cmdproxy-server
    depends_on:
      - backend
      - broker
    networks:
      - overlay
    environment:
      - CMDPROXY_RUST_LOG=TRACE
      - CMDPROXY_MONGODB_NAME=cmdproxy-testdb
      - CMDPROXY_MONGO_URL=mongodb://backend:27017
      - CMDPROXY_REDIS_URL=redis://broker:6379

# todo: use the cmdproxy.py
#  py-client:
#    build:
#      context: .
#      dockerfile: ./examples/Dockerfile.client-py
#    image: cmdproxy-example-client-py:0.2.2
#    container_name: cmdproxy-client
#    depends_on:
#      - backend
#      - broker
#    networks:
#      - overlay
#    environment:
#      - CMDPROXY_MONGODB_NAME=cmdproxy-testdb
#      - CMDPROXY_MONGO_URL=mongodb://backend:27017
#      - CMDPROXY_REDIS_URL=redis://broker:6379
#    profiles: ["py-client"]

  rs-client:
    build:
      context: .
      dockerfile: ./examples/Dockerfile.client-rs
    image: cmdproxy-example-client-rs:0.2.2
    container_name: cmdproxy-client
    depends_on:
      - backend
      - broker
    networks:
      - overlay
    environment:
      - CMDPROXY_RUST_LOG=TRACE
      - CMDPROXY_MONGODB_NAME=cmdproxy-testdb
      - CMDPROXY_MONGO_URL=mongodb://backend:27017
      - CMDPROXY_REDIS_URL=redis://broker:6379
    profiles: ["rs-client"]

networks:
  overlay:

