FROM rust:1.65

WORKDIR /home/projects/cmdproxy
RUN cargo init

COPY ./.cargo .cargo
COPY ./vendor vendor
COPY Cargo.toml ./
COPY Cargo.lock ./

RUN cargo build
RUN cargo clean -p cmdproxy

COPY ./src src
COPY ./examples examples

RUN cargo build --example client

CMD ["cargo", "run", "--example", "client"]
