FROM python:3.9

WORKDIR /home/projects/cmdproxy

RUN git clone https://www.github.com/limoiie/cmdproxy.py.git@0.0.1 /home/projects/cmdproxy

RUN python -m pip install .

CMD ["python", "./examples/client.py"]
